### ISSUE TITLE
Linker error when archiving tvOS app.

### ISSUE THREAD

**Issue by toshi0383** [CocoaPods/Rome#50]
```
ld: bitcode bundle could not be generated because '/Users/toshi0383/foo/app/Rome/RxSwift.framework/RxSwift' was built without full bitcode.
```

Any idea .. ?

**Comment by toshi0383** [comment]
How do you set BITCODE_GENERATION_MODE=bitcode to Rome ?

**Comment by ikesyo** [comment]
@toshi0383 Using `post_install` hook might help?

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
    end
  end
end
```

**Comment by toshi0383** [comment]
@ikesyo It worked !!
Also successfully uploaded archived app to iTunesConnect.
Thanks a lot !

p.s. I also added `carthage copy-frameworks` Build Phase b/c the app crashed due to `Image not found` error.
