### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by tcamin** [CocoaPods/Rome#55]
I'm having troubles trying to use the plugin with CP 1.2.0.rc.1.

Version 0.6, which gets installed via `gem install cocoapods-rome`, fails to install because of a conflict with fourflusher version (1.x required by cocoapods-rome, 2.x CP).

I was able to manually build and install latest master (v.0.7), however launching pod install with the sample Podfile doesn't work and fails with a `[!] Your Podfile requires that the plugin `cocoapods-rome` be installed. Please install it and try installation again.` 

`gem list`  shows cocoapods-rome to be correctly installed.

The Podfile I was trying to install is

```
platform :ios, '8.0'

plugin 'cocoapods-rome'

target 'caesar' do
    pod 'AFNetworking', '~>2.6'
end
```

**Comment by nikolasburk** [comment]
I am having installation issues as well. Here is what I did:

```
sudo gem install cocoapods-rome
```

Output:

```
Fetching: fourflusher-1.0.1.gem (100%)
Successfully installed fourflusher-1.0.1
Fetching: cocoapods-core-1.1.0.rc.2.gem (100%)
Successfully installed cocoapods-core-1.1.0.rc.2
Fetching: cocoapods-1.1.0.rc.2.gem (100%)
Successfully installed cocoapods-1.1.0.rc.2
Fetching: cocoapods-rome-0.7.0.gem (100%)
Successfully installed cocoapods-rome-0.7.0
Parsing documentation for fourflusher-1.0.1
Installing ri documentation for fourflusher-1.0.1
Parsing documentation for cocoapods-core-1.1.0.rc.2
Installing ri documentation for cocoapods-core-1.1.0.rc.2
Parsing documentation for cocoapods-1.1.0.rc.2
Installing ri documentation for cocoapods-1.1.0.rc.2
Parsing documentation for cocoapods-rome-0.7.0
Installing ri documentation for cocoapods-rome-0.7.0
Done installing documentation for fourflusher, cocoapods-core, cocoapods, cocoapods-rome after 4 seconds
4 gems installed
```

Added Podfile: 

```
platform :osx, '10.10'

plugin 'cocoapods-rome'

target 'caesar' do
  pod 'Alamofire'
end
```

Ran `pod install`

Output:

```
---------------------------------------------
Error loading the plugin `cocoapods-rome-0.7.0`.

Gem::ConflictError - Unable to activate cocoapods-rome-0.7.0, because fourflusher-2.0.1 conflicts with fourflusher (~> 1.0.0)
/Users/nburk/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2112:in `raise_if_conflicts'
/Users/nburk/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1280:in `activate'
/Users/nburk/.rvm/gems/ruby-2.1.6@global/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require'
/Users/nburk/.rvm/gems/ruby-2.1.6@global/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Users/nburk/.rvm/gems/ruby-2.1.6@global/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:30:in `map'
/Users/nburk/.rvm/gems/ruby-2.1.6@global/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Users/nburk/.rvm/gems/ruby-2.1.6@global/gems/claide-1.0.1/lib/claide/command.rb:326:in `block in run'
/Users/nburk/.rvm/gems/ruby-2.1.6@global/gems/claide-1.0.1/lib/claide/command.rb:325:in `each'
/Users/nburk/.rvm/gems/ruby-2.1.6@global/gems/claide-1.0.1/lib/claide/command.rb:325:in `run'
/Users/nburk/.rvm/gems/ruby-2.1.6@global/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/nburk/.rvm/gems/ruby-2.1.6@global/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/nburk/.rvm/gems/ruby-2.1.6/bin/pod:23:in `load'
/Users/nburk/.rvm/gems/ruby-2.1.6/bin/pod:23:in `<main>'
/Users/nburk/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `eval'
/Users/nburk/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `<main>'
---------------------------------------------

[!] Your Podfile requires that the plugin `cocoapods-rome` be installed. Please install it and try installation again.
```

**Comment by AliSoftware** [comment]
Thanks for the bug report

Indeed, this is already fixed in `master`, but we need to release a new version of `cocoagpods-rome` (0.8.0) to push that fix on RubyGems. We'll hopefully do that ASAP, sorry for the inconvenience.

In the meantime, if you don't want to wait too long for the new release, you could use the `master` of `cocoapods-rome` directly instead. To do that, simply use a `Gemfile` like the following one:

```
source 'https://rubygems.org'

gem 'cocoapods', '~> 1.2'
gem 'cocoapods-rome', :git => 'https://github.com/CocoaPods/cocoapods-rome.git'
```
Then use `bundle install` to install the gems listed in your `Gemfile`, then `bundle exec pod install` (and other `bundle exec pod xxx` commands instead of `pod xxx` directly) to run cocoapods using the versions listed in your Gemfile.
(You might need to install `gem install bundler` if you don't have bundler on your Mac already)

For more information about Gemfiles, read https://guides.cocoapods.org/using/a-gemfile.html

**Comment by AliSoftware** [comment]
CocoaPods-Rome 0.8.0 has finally been released 🎉 you should be able to install and use it with CocoaPods 1.2 now!

**Comment by MeGaPk** [comment]
@AliSoftware maybe you close this issue :)?

**Comment by AliSoftware** [comment]
@MeGaPk Indeed we can close this issue.

I don't have the rights to do so (no "Close Issue" button for me), it has to be done by the issue author or by an owner of the repo though.

**Comment by MeGaPk** [comment]
@AliSoftware sorry :(

@neonichu @tcamin Can you please close this issue? If problem has resolved.
