### ISSUE TITLE
Specifying xcconfig params (such as SWIFT_VERSION) for individual pods

### ISSUE THREAD

**Issue by jasonm23** [CocoaPods/Rome#60]
As pod package developers don't expect Cocoapods to manage building frameworks using Rome, podspecs don't include xcconfig / build parameters, such as `SWIFT_VERSION`.

So when trying to run `pod install` or `pod update` with `plugin 'cocoapods-rome'` in the `Podfile` there are often errors about missing build params.

I wonder if Rome could read additional custom params from the `Podfile` so that we could supply the missing build params.  (Instead of requiring the pod authors to update their podspecs to be compatible!)

Maybe there's another way out of this problem too?

**Comment by tcamin** [comment]
Hi, I had the same problem and just opened PR #61 to fix that

HTH

**Comment by jasonm23** [comment]
Thank you @tcamin

**Comment by orta** [comment]
Yep agree, closing because of the post_install hook
