### ISSUE TITLE
Bundles are not placed to Rome folder

### ISSUE THREAD

**Issue by TomasLinhart** [CocoaPods/Rome#66]
I tried Rome with ZendeskSDK that is precompiled and comes with bundles. Rome correctly puts the precompiled frameworks in Rome folder, but it ignores the bundles.

**Comment by orta** [comment]
Sounds like a real bug, would you like to try fix this?

**Comment by TomasLinhart** [comment]
I see it could be done in:

```ruby
umbrella.specs.each do |spec|
  consumer = spec.consumer(umbrella.platform_name)
  file_accessor = Pod::Sandbox::FileAccessor.new(sandbox.pod_dir(spec.root.name), consumer)
  frameworks += file_accessor.vendored_libraries
  frameworks += file_accessor.vendored_frameworks
end
```

Right? How would I get `resources` field from Podspec there?

**Comment by orta** [comment]
I’d expect spec to have a .resources
